# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 01:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20160607_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, help_text='Do you name your car? We like it! Tell us the name of your.car.', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s+]+$', 'Car name must have only alphanumeric characters')], verbose_name='Car name'),
        ),
    ]
