# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20160611_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilchange',
            name='date',
            field=models.DateField(verbose_name='date changed'),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='date',
            field=models.DateField(verbose_name='date refueled'),
        ),
    ]
