# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20160611_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuel',
            name='fuel_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='liters',
            field=models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
