# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_userbotconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbotconversation',
            name='chat',
            field=models.BigIntegerField(unique=True),
        ),
    ]
